# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pipeline.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'pipeline.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epipeline.proto\x12\x08pipeline\"\x1b\n\tFloatList\x12\x0e\n\x06values\x18\x01 \x03(\x02\"\x1c\n\nStringList\x12\x0e\n\x06values\x18\x01 \x03(\t\"\x1b\n\tBytesList\x12\x0e\n\x06values\x18\x01 \x03(\x0c\"\xa0\x01\n\x05Value\x12\x0b\n\x01\x62\x18\x01 \x01(\x0cH\x00\x12\x0b\n\x01s\x18\x02 \x01(\tH\x00\x12\x0b\n\x01\x66\x18\x05 \x01(\x02H\x00\x12!\n\x02\x62\x62\x18\x06 \x01(\x0b\x32\x13.pipeline.BytesListH\x00\x12\"\n\x02ss\x18\x07 \x01(\x0b\x32\x14.pipeline.StringListH\x00\x12!\n\x02\x66\x66\x18\n \x01(\x0b\x32\x13.pipeline.FloatListH\x00\x42\x06\n\x04kind\"\x89\x01\n\x08\x45nvelope\x12\x13\n\x0b\x63onfig_json\x18\x01 \x01(\t\x12*\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x1c.pipeline.Envelope.DataEntry\x1a<\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.pipeline.Value:\x02\x38\x01\x32\x44\n\x0fPipelineService\x12\x31\n\x07Process\x12\x12.pipeline.Envelope\x1a\x12.pipeline.Envelopeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pipeline_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENVELOPE_DATAENTRY']._loaded_options = None
  _globals['_ENVELOPE_DATAENTRY']._serialized_options = b'8\001'
  _globals['_FLOATLIST']._serialized_start=28
  _globals['_FLOATLIST']._serialized_end=55
  _globals['_STRINGLIST']._serialized_start=57
  _globals['_STRINGLIST']._serialized_end=85
  _globals['_BYTESLIST']._serialized_start=87
  _globals['_BYTESLIST']._serialized_end=114
  _globals['_VALUE']._serialized_start=117
  _globals['_VALUE']._serialized_end=277
  _globals['_ENVELOPE']._serialized_start=280
  _globals['_ENVELOPE']._serialized_end=417
  _globals['_ENVELOPE_DATAENTRY']._serialized_start=357
  _globals['_ENVELOPE_DATAENTRY']._serialized_end=417
  _globals['_PIPELINESERVICE']._serialized_start=419
  _globals['_PIPELINESERVICE']._serialized_end=487
# @@protoc_insertion_point(module_scope)
