#!/usr/bin/env python3
"""Generate registry/index.json, registry/ports.json, the README box table,
and the CI build matrix.

Everything downstream of a manifest is produced here, so no list of boxes is
ever maintained by hand. The repo this registry was split out of had a
hand-written publish matrix in its workflow; by the time it had 11 boxes the
matrix listed 8, and nobody noticed that three boxes were silently never built.

    python3 tools/build_index.py            # write index + README table
    python3 tools/build_index.py --check    # verify they are current (CI)
    python3 tools/build_index.py --matrix   # print the CI matrix as JSON
"""

import argparse
import json
import re
import sys

from _registry import (assign_ports, image_ref, load_all, load_ports,
                       registries_of, repo_root)

BEGIN = "<!-- BEGIN BOXES -->"
END = "<!-- END BOXES -->"

GI_BEGIN = "# BEGIN ASSETS (generated by tools/build_index.py)"
GI_END = "# END ASSETS"


def build_index(manifests: list[dict], ports: dict) -> dict:
    boxes = []
    for m in manifests:
        boxes.append({
            "name": m["name"],
            "key": m["key"],
            # Permanent host port from registry/ports.json, issued in arrival
            # order. A fleet generator uses this rather than counting from a
            # base, so a box answers on the same port in every fleet.
            "port": ports[m["name"]],
            "version": m["version"],
            "summary": m["summary"],
            "runtime": m["runtime"],
            "status": m.get("status", "experimental"),
            "tags": sorted(m.get("tags", [])),
            "commands": m["commands"]["values"],
            "default_command": m["commands"].get("default"),
            "session": m.get("session"),
            "security": m.get("security") or {"profile": "standard"},
            "maintainers": [x["github"] for x in m["maintainers"]],
            "image": {
                "repository": m["image"]["repository"],
                "registries": registries_of(m),
                "approx_size_gb": m["image"].get("approx_size_gb"),
                "refs": {r: image_ref(m, r) for r in registries_of(m)},
            },
            "data": m["data"],
            "constraints": m.get("constraints", []),
            "path": f"boxes/{m['name']}",
        })
    boxes.sort(key=lambda b: b["name"])
    return {
        "schema": "registry/schema.json",
        "generated_by": "tools/build_index.py",
        "count": len(boxes),
        "boxes": boxes,
    }


def readme_table(index: dict) -> str:
    rows = ["| Box | Key | Runtime | Port | What it does | Tags |",
            "|---|---|---|---|---|---|"]
    for b in index["boxes"]:
        tags = " ".join(f"`{t}`" for t in b["tags"]) or ""
        rows.append(f"| [`{b['name']}`](boxes/{b['name']}) | `{b['key']}` | "
                    f"{b['runtime']} | {b['port']} | {b['summary']} | {tags} |")
    return "\n".join(rows)


def splice(text: str, table: str) -> str:
    if BEGIN not in text or END not in text:
        raise SystemExit(f"README.md has no {BEGIN} / {END} markers")
    head, _, rest = text.partition(BEGIN)
    _, _, tail = rest.partition(END)
    return f"{head}{BEGIN}\n{table}\n{END}{tail}"


def gitignore_block(manifests: list[dict]) -> str:
    """Declared assets are fetched, never committed - so git must ignore them."""
    paths = sorted(f"boxes/{m['name']}/{a['path']}"
                   for m in manifests for a in (m.get("assets") or []))
    body = "\n".join(paths) if paths else "# (no declared assets)"
    return f"{GI_BEGIN}\n{body}\n{GI_END}"


def splice_gitignore(text: str, block: str) -> str:
    if GI_BEGIN in text and GI_END in text:
        head, _, rest = text.partition(GI_BEGIN)
        _, _, tail = rest.partition(GI_END)
        return f"{head}{block}{tail}"
    sep = "" if text.endswith("\n") or not text else "\n"
    return f"{text}{sep}\n{block}\n"


def codeowners(manifests: list[dict]) -> str:
    """Box maintainers review their own box. Generated, so it cannot go stale."""
    lines = [
        "# Generated by tools/build_index.py from each box.yaml's maintainers.",
        "# Edit the manifest, not this file.",
        "",
        "# The contract and the tooling belong to the registry maintainers.",
        "/contract/     @jpcosteira",
        "/tools/        @jpcosteira",
        "/registry/     @jpcosteira",
        "/.github/      @jpcosteira",
        "",
    ]
    for m in sorted(manifests, key=lambda x: x["name"]):
        owners = " ".join(f"@{x['github']}" for x in m["maintainers"])
        lines.append(f"/boxes/{m['name']}/".ljust(40) + owners)
    return "\n".join(lines) + "\n"


def build_matrix(manifests: list[dict]) -> list[dict]:
    """One entry per box, for the publish workflow's matrix."""
    return [{"name": m["name"],
             "repository": m["image"]["repository"],
             "version": m["version"],
             "registries": ",".join(registries_of(m)),
             "platforms": ",".join(m["image"].get("platforms", ["linux/amd64"])),
             "context": f"boxes/{m['name']}",
             "key": m["key"]}
            for m in sorted(manifests, key=lambda x: x["name"])]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--matrix", action="store_true")
    args = ap.parse_args()

    root = repo_root()
    manifests = load_all(root)

    ledger, newly = assign_ports(load_ports(root), manifests)
    ports = ledger["ports"]

    if args.matrix:
        print(json.dumps({"box": build_matrix(manifests)}))
        return 0

    index = build_index(manifests, ports)
    index_text = json.dumps(index, indent=2) + "\n"
    index_path = root / "registry" / "index.json"

    ports_path = root / "registry" / "ports.json"
    ports_text = json.dumps(ledger, indent=2) + "\n"
    old_ports_text = ports_path.read_text() if ports_path.is_file() else ""

    readme_path = root / "README.md"
    readme_text = readme_path.read_text()
    new_readme = splice(readme_text, readme_table(index))

    gi_path = root / ".gitignore"
    gi_text = gi_path.read_text() if gi_path.is_file() else ""
    new_gi = splice_gitignore(gi_text, gitignore_block(manifests))

    co_path = root / ".github" / "CODEOWNERS"
    co_text = co_path.read_text() if co_path.is_file() else ""
    new_co = codeowners(manifests)

    if args.check:
        stale = []
        if not index_path.is_file() or index_path.read_text() != index_text:
            stale.append("registry/index.json")
        if ports_text != old_ports_text:
            stale.append("registry/ports.json"
                         + (f" (unassigned: {', '.join(newly)})" if newly else ""))
        if new_readme != readme_text:
            stale.append("README.md (box table)")
        if new_gi != gi_text:
            stale.append(".gitignore (asset list)")
        if new_co != co_text:
            stale.append(".github/CODEOWNERS")
        if stale:
            print("out of date, run tools/build_index.py: " + ", ".join(stale),
                  file=sys.stderr)
            return 1
        print(f"index and README current ({index['count']} boxes)")
        return 0

    index_path.write_text(index_text)
    ports_path.write_text(ports_text)
    readme_path.write_text(new_readme)
    gi_path.write_text(new_gi)
    co_path.parent.mkdir(parents=True, exist_ok=True)
    co_path.write_text(new_co)
    print(f"wrote registry/index.json, registry/ports.json, the README table, "
          f"the .gitignore asset list and .github/CODEOWNERS "
          f"({index['count']} boxes)")
    for name in newly:
        print(f"  new box {name}: host port {ports[name]} (next in sequence)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
